name = "RdvSpeakers Theme Hugo"
license = "MIT"
licenselink = "https://github.com/RdvSpeakers/rdvspeakers-theme-hugo/LICENSE"
description = "A theme for a conference website. Based on GDG Toulouse's DevFest Theme Hugo"
homepage = "https://github.com/RdvSpeakers/rdvspeakers-theme-hugo"
tags = ["conference", "Rendez-vous des Speakers"]
features =  ["conference", "responsive", "l10n", "google-analytics"]
min_version = "0.50"

[author]
  name = "Les Rendez-vous des Speakers"
  homepage = "//github.com/RdvSpeakers"
